DELIMITER $$
USE AUTHENTICATION$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `get_users_groups`(IN user_name VARCHAR(50), IN pass VARCHAR(50))
BEGIN
	DECLARE EXIT HANDLER FOR NOT FOUND 
		BEGIN 
			INSERT INTO LOG(EVENT_MSG) VALUES (CONCAT("Unauthorized access USER:",user_name," PASWORD:",pass));
		END;
	SELECT 
		G.ID,G.GROUP_NAME,G.DESCRIPTION,IF(G.ID=U.DEFAULT_GROUP_ID,1,0) AS DEFAULT_GROUP, G.ACCESSOR, UG.ACCESSOR_ID
	FROM 
		USERS U INNER JOIN GROUPS G INNER JOIN USER_GROUP_MAP UG
	ON 
		(U.ID = UG.USER_ID AND G.ID = UG.GROUP_ID) 
	WHERE
		U.USER_NAME=user_name AND U.PASSWORD=pass AND U.ENABLED=1 AND G.ENABLED=1 AND (U.PASSWORD_EXPIRATION IS NULL OR U.PASSWORD_EXPIRATION > NOW())
	ORDER BY 
		DEFAULT_GROUP DESC;
END$$
DELIMITER ;
